## Table of Content
- Create NumPy Arrays
- Key Attributes of NumPy Arrays
- Operations on NumPy Arrays
- Dimensions in NumPy Arrays
- NumPy Arrays vs Python Lists
- Data Allocation in Numpy Array

  ## Note:
      -  Numpy aaray's object -> allow us to work with array.
      -  Array's object called as ndarray.
      - array() function are used to create numpy array

## Create NumPy Arrays:  

In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [6]:
#simple array / 0-D array -> also called as "scalar"
a=np.array(25)
print(a)
print()

#1-D -> also called as "vector"
x= np.array([1,56,'s',67])
print(x)
print()

#2-D -> also called as "matrix"
y=np.array([[11,78,45],[23,56,44]])
print(y)
print()

#3-D -> also called as "tensor"
z=np.array([[[2,5,6,5],[2,5,7,9],[12,78,90,34]]])
print(z)

25

['1' '56' 's' '67']

[[11 78 45]
 [23 56 44]]

[[[ 2  5  6  5]
  [ 2  5  7  9]
  [12 78 90 34]]]


## Key Attributes of NumPy Arrays
 - ndim :- it returns number of dimentions of array (1D,2D...)
 - shape :- it returns dimentions of array  (rows, columns)
 - dtype :- it returns datatype of elements (int32, int64, float64, etc.)

In [9]:
arr2=np.array(['s',3,6,7])
arr3=np.array([[2,4,89],[3,78,90]])
arr4=np.array([1,6,8.9],ndmin=8) #you can define the number of dimensions by using the ndmin argument.
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)
print()
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)
print()
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)

1
2
8

(4,)
(2, 3)
(1, 1, 1, 1, 1, 1, 1, 3)

<U21
int64
float64


## Operations on NumPy Arrays


In [14]:
#addition
arr1=np.array([8,9])
arr2=np.array([2,7])
print(arr1 + arr2)
print()

#matrix multiplication
arr1=np.array([[4,6],[8,3]])
arr1=np.array([[2,9],[8,3]])
print(np.dot(arr1 , arr2))
print()
print(np.matmul(arr1 , arr2))
print()
print((arr1 @ arr2))

[10 16]

[67 37]

[67 37]

[67 37]


## 1. np.dot()
- Dot product for vectors
- Matrix multiplication for 2D arrays
- But behaves differently for 1D & >2D arrays
## 2. np.matmul()
- Always performs matrix multiplication
- Works for 2D arrays and higher dimensions
- Does NOT do element-wise multiplication
## 3. @ Operator
- The matrix multiplication operator
- Introduced in Python 3.5
- Same as np.matmul()

## NumPy Arrays vs Python Lists
- Fixed Size: Arrays have a fixed size, while lists can dynamically grow.
- Homogeneous Data: Arrays require uniform data types; lists can store mixed types.
- Performance: Arrays are faster due to their optimized implementation.
- Memory Efficiency: Arrays use contiguous memory blocks, unlike lists.

## Numpy Array Indexing
- used to access ellements or subsets of data within an array.
- This feature allows us to retrieve, modify and manipulate data at specific positions or ranges helps in making it easier to work with large datasets.

In [15]:
## 1. 1-D indexing
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print()
arr1=np.array([23,90,67,89,45,90])
print(arr1[0]+arr1[4])

10

68


In [18]:
# 2-D indexing:2D Arrays: We can access elements by specifying both row and column indices like matrix[row, column].
arr = np.array([[10, 20, 30],[ 40, 50,90],[3,7,9]])
print(arr[0,2])
print(arr[1,1])
print(arr[2,0])

30
50
3


In [19]:
# #3-D indexing 
# 3D Arrays: It can be visualized as a stack of 2D arrays, we need three indices-
# - Depth: Specifies the 2D slice.
# - Row: Specifies the row within the slice.
# - Column: Specifies the column within the row.
arr = np.array([
                 [[10, 20, 30],
                 [ 40, 50,90],
                 [3,7,9]],
                 
                [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]
                ])
print(arr[1,1,2])

15


In [20]:
#negative indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


## Slicing arrays
- Slicing in python means taking elements from one given index to another given index.
- We pass slice instead of index like this: [start:end].
- We can also define the step, like this: [start:end:step].
- If we don't pass start its considered 0
- If we don't pass end its considered length of array in that dimension
- If we don't pass step its considered 1


In [1]:
import numpy as np


In [9]:
#Slicing 1-D Arrays
arr1=np.array([1,6,9,90,67,89,3,45,31])
print(arr1)
print(arr1[0:6])
print()

print(arr1)
print(arr1[:4])
print()

print(arr1)
print(arr1[:4])
print()
print(arr1)
print(arr1[::2])

print()
print(arr1)
print(arr1[1:5:2])


[ 1  6  9 90 67 89  3 45 31]
[ 1  6  9 90 67 89]

[ 1  6  9 90 67 89  3 45 31]
[ 1  6  9 90]

[ 1  6  9 90 67 89  3 45 31]
[ 1  6  9 90]

[ 1  6  9 90 67 89  3 45 31]
[ 1  9 67  3 31]

[ 1  6  9 90 67 89  3 45 31]
[ 6 90]


In [8]:
#Slicing 2-D Arrays
arr = np.array([[10, 20, 30], [40, 5, 66], [70, 88, 94]])
print("Array:")
print(arr)
print()
print(arr[[0,2]]) #Accessing the First and Last row of a 2D NumPy array

print()
arr = np.array([[10, 20, 30], [40, 5, 66], [70, 88, 94]])
print("Array:")
print(arr)
print()
print(arr[[1]])
print()

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

Array:
[[10 20 30]
 [40  5 66]
 [70 88 94]]

[[10 20 30]
 [70 88 94]]

Array:
[[10 20 30]
 [40  5 66]
 [70 88 94]]

[[40  5 66]]

[[2 3 4]
 [7 8 9]]


In [10]:
# In 3D Arrays

n_arr = np.array([[[10, 25, 70], [30, 45, 55], [20, 45, 7]], [[50, 65, 8], [70, 85, 10], [11, 22, 33]]])
print("Array:")
print(n_arr)
print()
res_arr = n_arr[:,[1]]
print("Accessed Rows:")
print(res_arr)
print()
n_arr = np.array([[[10, 25, 70], [30, 45, 55], [20, 45, 7]], 
                 [[50, 65, 8], [70, 85, 10], [11, 22, 33]],
                 [[19, 69, 36], [1, 5, 24], [4, 20, 96]]])
print("Array:")
print(n_arr)

res_arr = n_arr[:,[0, 2]]
print("Accessed Rows:")
print(res_arr)

Array:
[[[10 25 70]
  [30 45 55]
  [20 45  7]]

 [[50 65  8]
  [70 85 10]
  [11 22 33]]]

Accessed Rows:
[[[30 45 55]]

 [[70 85 10]]]

Array:
[[[10 25 70]
  [30 45 55]
  [20 45  7]]

 [[50 65  8]
  [70 85 10]
  [11 22 33]]

 [[19 69 36]
  [ 1  5 24]
  [ 4 20 96]]]
Accessed Rows:
[[[10 25 70]
  [20 45  7]]

 [[50 65  8]
  [11 22 33]]

 [[19 69 36]
  [ 4 20 96]]]


## Data Types in Python
By default Python have these data types:
- strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
- integer - used to represent integer numbers. e.g. -1, -2, -3
- float - used to represent real numbers. e.g. 1.2, 42.42
- boolean - used to represent True or False.
- complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

## Converting Data Type on Existing Arrays
- The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
- The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
- The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float   and int for integer.

In [16]:
#Checking the Data Type of an Array
print("Checking the Data Type of an Array:")
arr=np.array([1.1,1.2,1.9])
print(arr.dtype)
print()
#Creating Arrays With a Defined Data Type
print("Creating Arrays With a Defined Data Type:")
arr1=np.array([1,6,8],dtype='S')
print(arr1)
print(arr1.dtype)
print()

arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)
print()

# Converting Data Type on Existing Arrays
print(" Converting Data Type on Existing Arrays")
arr=np.array([1.2,3.7,9.5])
print(arr)
print()
newarr=arr.astype('i')
print(newarr)

Checking the Data Type of an Array:
float64

Creating Arrays With a Defined Data Type:
[b'1' b'6' b'8']
|S1

[1 2 3 4]
int32

 Converting Data Type on Existing Arrays
[1.2 3.7 9.5]

[1 3 9]


## NumPy Array Copy vs View
The Difference Between Copy and View
- The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
- The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect - the copy.
- The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [18]:
#Copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)
print()

#view
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]

[42  2  3  4  5]
[42  2  3  4  5]


## NumPy Array Shape and Reshape and Resize
- The shape of an array is the number of elements in each dimension.
- NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements

- Reshaping means changing the shape of an array.
- The shape of an array is the number of elements in each dimension.
- By reshaping we can add or remove dimensions or change number of elements in each dimension.

- The numpy.resize() function is used to change the size of an existing NumPy array.
- It modifies the array permanently and adjusts its shape to the new dimensions.
- If the new shape requires more elements than available, NumPy repeats the array elements. If less space is required, elements are truncated.

- Modifies the array permanently
✔ Can increase OR decrease number of elements
❗ If more elements needed → NumPy repeats or fills zeros
❗ If fewer elements needed → it deletes extra elements

👉 reshape() only changes shape
resize() changes shape + size
 

In [22]:
#shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
print()
arr1 = np.array([
                 [[10, 20, 30],
                 [ 40, 50,90],
                 [3,7,9]],
                 
                [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]
                ])
print(arr1.shape)
print()
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

(2, 4)

(2, 3, 3)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [25]:
#reshape
print("1-D to 2-D")
a = np.array([1, 2, 3, 4, 5, 6])
print(a.reshape(2,3))
print()
print("1-D to 3-D")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)
print()
# This example demonstrates the use of -1 when one dimension is unknown. NumPy calculates that missing dimension automatically.
#Explanation: a.reshape(3, -1) tells NumPy to create 3 rows, and it computes the remaining dimension as 4 columns, since 12 ÷ 3 = 4.
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
r = a.reshape(3, -1)
print(r)

1-D to 2-D
[[1 2 3]
 [4 5 6]]

1-D to 3-D
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [24]:
print(a.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [26]:
#resize
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((2, 3))
print(arr)
print()
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((3, 4))
print(arr)
print()
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((3, 4))
print(arr)

[[1 2 3]
 [4 5 6]]

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


## NumPy Array Iterating
- Iterating means going through elements one by one.
- As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
- If we iterate on a 1-D array it will go through each element one by one.

## Iterating Arrays Using nditer()
- np.nditer(arr) — iterate over each scalar element of arr (works for any dimension: 1D, 2D, 3D, ...)

**Why use nditer instead of nested loops?**
- If you had a 5-D array, writing 5 nested for loops is messy. nditer gives a single simple loop that works for any number of dimensions.

## Iterating Array With Different Data Types
- We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
- NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

## Enumerated Iteration Using ndenumerate()
- np.ndenumerate(arr) — iterate (index, value) pairs; gives you the multi-index (tuple of coordinates) for each element

In [40]:
#Iterate on the elements of the following 1-D array:
arr = np.array([1, 2, 3])
for x in arr:
  print(x)
print()
#Iterate on the elements of the following 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)
print()
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)
print()

#Iterate on the elements of the following 3-D array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)
print()
for x in arr:
    for y in x:
        for z in y:
            print(z)
print()
#Iterate on the elements usinf np.nditer() of the following 3-D array:
arr = np.array([[[1,2], [3,4]],
                [[5,6], [7,8]]])
for x in np.nditer(arr):
    print(x)
print()
#Iterate on the elements using np.nditer() for Iterating Array With Different Data Types
arr = np.array([1, 2, 3])            # dtype=int
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x,type(x))

# op_dtypes=['S'] tells the iterator to present each element as bytes/string.
# flags=['buffered'] allows nditer to create a temporary buffer with the requested dtype;
# without buffered you d get an error because dtype conversion cannot be done in-place.
print()
# ndenumerate — give index with value (very handy)
#1D example
arr = np.array([10,20,30])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

print()
#2D example
arr = np.array([[1,2,3],
                [4,5,6]])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

1
2
3

[1 2 3]
[4 5 6]

1
2
3
4
5
6

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

1
2
3
4
5
6
7
8
9
10
11
12

1
2
3
4
5
6
7
8

np.bytes_(b'1') <class 'numpy.ndarray'>
np.bytes_(b'2') <class 'numpy.ndarray'>
np.bytes_(b'3') <class 'numpy.ndarray'>

(0,) 10
(1,) 20
(2,) 30

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [39]:
#Iterating with a step (skip elements) :You can slice the array first and iterate the slice.
#Explanation :arr[:, ::2] creates a smaller view: take all rows, every 2nd column. Then nditer walks those elements.
arr = np.array([[1,2,3,4],
                [5,6,7,8]])
# take every second column (columns 0,2)
for x in np.nditer(arr[:, ::2]):
    print(x)
print()

#Modify elements while iterating (in-place write):Use op_flags=['readwrite'] to let the iterator write back to the array.
# Explanation: x is a 0-d numpy scalar view; x[...] = writes back to the array because we set readwrite.
arr = np.arange(1,7).reshape(2,3)   # [[1,2,3],[4,5,6]]
for x in np.nditer(arr, op_flags=['readwrite']):
    x[...] = x * 10     # multiply each element by 10
print(arr)
print()


#External loop: return chunks instead of scalars,flags=['external_loop'] makes the iterator yield 1-D arrays (faster for some ops).
#Explanation :The iterator returns each row (since memory layout is row-major). Good when you want to operate row-by-row.
arr = np.array([[1,2,3], [4,5,6]])
for chunk in np.nditer(arr, flags=['external_loop'], order='C'):
    print(chunk, type(chunk))
print()

# Order control: C vs Fortran ,Default is C order. You can iterate in Fortran (column-major) order:
arr = np.array([[1,2,3],
                [4,5,6]])
for x in np.nditer(arr, order='F'):
    print(x, end=' ')
# prints column-wise: 1 4 2 5 3 
print()

1
3
5
7

[[10 20 30]
 [40 50 60]]

[1 2 3 4 5 6] <class 'numpy.ndarray'>

1 4 2 5 3 6 


In [38]:
arr = np.array([[10,20,30],[1,6,8]])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 10
(0, 1) 20
(0, 2) 30
(1, 0) 1
(1, 1) 6
(1, 2) 8


## Joining NumPy Arrays
- Joining means putting contents of two or more arrays in a single array.
- In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
- We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis.
    If axis is not explicitly passed, it is taken as 0.

In [42]:
#1-D array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [43]:
#2-D array
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


**Joining Arrays Using Stack Functions**
- Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
- We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
- We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [48]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)
print()
#Stacking Along Rows ,NumPy provides a helper function: hstack() to stack along rows.
arr = np.hstack((arr1, arr2))
print(arr)
print()

#Stacking Along Columns,NumPy provides a helper function: vstack()  to stack along columns.
arr = np.vstack((arr1, arr2))
print(arr)
print()
c= np.stack((arr1, arr2),axis=-1)
print(c)
#Stacking Along Height (depth) ,NumPy provides a helper function: dstack() to stack along height, which is the same as depth.
arr = np.dstack((arr1, arr2))
print(arr)


[[1 4]
 [2 5]
 [3 6]]

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]
[[[1 4]
  [2 5]
  [3 6]]]
